### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by ozvereva** [Minras/MinrasLovesYouUa#6]
the phrase "ти мене кохаєшь?" should be "ти мене кохаєш" without the 'ь' letter

**Comment by Minras** [comment]
oh noes!

**Comment by Minras** [comment]
Fixed in https://github.com/Minras/MinrasLovesYouUa/commit/54daf6221cdcd7809217dc022c42351f294044f3

Will appear in the next release.

**Comment by ozvereva** [comment]
tykva darling
